DO NOT REVIEW
SouthridgeCorp/player-outcome-predictor pull request #63
Opened 2023-02-08 01:34 UTC by swati0308

2023-02-08 01:35 UTC, swati0308 commented on pages/6_📋_Review_Predictive_Simulations.py
> +            metrics_to_show_df = metric_stats_df[['name', 'number_of_matches',
We will show metrics in the very end after processing a few more data points

2023-02-08 14:02 UTC, gireesh-fractal requested changes
@swati0308 mostly looks okay, just found one small issue. I have initiate a BI model run on my laptop. Let's review the results tomorrow morning and then decide next steps.

2023-02-08 14:02 UTC, gireesh-fractal commented on pages/6_📋_Review_Predictive_Simulations.py
> +                                f"{metrics_to_show_df.shape[0]}")
out of here should be out of number of batters

2023-02-10 01:35 UTC, gireesh-fractal approved these changes

2023-02-13 01:02 UTC, merged